project:
  type: book
  output-dir: _book

filters:
  - haskell-error-filter.lua  # 생성한 파일명

book:
  title: "Haskell 프로그래밍"
  author: "저자 이름"
  date: today
  language: ko
  chapters:
    - index.qmd
    - ch00.qmd # 머리말 (unnumbered 예시)
    - ch01.qmd
    - ch02.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    title-block-style: none   # 타이틀 블록 자체를 생성하지 않음
    number-sections: true
    highlight-style: github
    # echo: true
    # keep-ipynb: false
  pdf:
    documentclass: scrbook
    classoption:
      - twoside
      - 10pt
    pdf-engine: xelatex
    # mainfont: "Noto Serif CJK KR"
    # fontoptions: "Ligatures=TeX"
    # sansfont: "Noto Sans CJK KR"
    # monofont: "Hack"
    include-in-header: latex/preamble.tex
    keep-tex: true
    number-sections: true
    colorlinks: true
    highlight-style: github
    # echo: true
    # keep-ipynb: false
    geometry:
      - paperwidth=7in
      - paperheight=9.1in
      - top=0.8in
      - bottom=0.8in
      - inner=0.7in
      - outer=0.9in
      - headheight=14pt
      - headsep=0.25in
      - footskip=0.25in
      - includeheadfoot
execute:
  execute-notebooks: false
  enabled: false
  freeze: true
  # echo: true
